---
general:
  pipeline: "sap-ui5-cf"
stages:
  testStage:
    enable: false
  deployStage:
    enable: false
  tmsStage:
    enable: true
  malwareScanStage:
    enable: true
steps:
  mtaBuild:
    applicationName: ""
  tmsUpload:
    nodeName: "QLT_Upload"
    credentialsId: "ctmstest"

