---
general:
  pipeline: "sap-ui5-cf"
stages:
  testStage:
    enable: false
  deployStage:
    enable: true
  tmsStage:
    enable: true
  malwareScanStage:
    enable: true
steps:
  mtaBuild:
    applicationName: ""
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
      org: "0d46997dtrial"
      space: "dev"
      credentialsId: "cockpitaccess"
  tmsUpload:
    nodeName: "QAS_Upload"
    credentialsId: "ctmstest"
